# Generated by Django 5.1.8 on 2026-04-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, max_length=128, null=True)),
                ('full_name', models.CharField(blank=True, max_length=256, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=256, null=True)),
                ('medical_license_number', models.CharField(blank=True, max_length=128, null=True)),
                ('ngo_registration_number', models.CharField(blank=True, max_length=128, null=True)),
                ('specialization', models.CharField(blank=True, max_length=256, null=True)),
                ('mission_statement', models.TextField(blank=True, null=True)),
                ('q1', models.TextField(blank=True, null=True)),
                ('q2', models.TextField(blank=True, null=True)),
                ('q3', models.TextField(blank=True, null=True)),
                ('q4', models.TextField(blank=True, null=True)),
                ('signature_filename', models.CharField(max_length=255)),
                ('signature_base64', models.TextField(blank=True, null=True)),
                ('unique_id', models.CharField(blank=True, max_length=128, null=True)),
                ('ollama_summary', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=32)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
