# Generated by Django 5.1.8 on 2026-04-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=256)),
                ('patient_name', models.CharField(blank=True, max_length=256, null=True)),
                ('patient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('patient_phone', models.CharField(blank=True, max_length=32, null=True)),
                ('appointment_type', models.CharField(choices=[('physical', 'physical'), ('virtual', 'virtual')], default='physical', max_length=32)),
                ('hospital', models.CharField(blank=True, max_length=256, null=True)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=32)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
